# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='FormResponse',
        ),
    ]
